name: Mahime
main: com.github.owatakun.mahime.Mahime
version: 1.1.0
description: Mahime plugin.
commands:
  mahime:
    description: Give the all the privileges of Mahime
    aliases: mhm
    usage: |
           /mahime gkit  - kit一斉配布
           /mahime gskit <kitName> [Player] - 指定したkitを配布
           /mahime reload - 設定ファイル再読み込み
           /mahime kitlist - 読み込まれている職一覧表示(config.ymlの値)
           /mahime rc - 登録されたポイントからランダムに巡礼用チェスト配置
           /mahime rc edit start - EditModeの開始
           /mahime rc edit end - EditModeの終了
    permission: mahime.admin
    permission-message: You don't have permission!
permissions:
  mahime.*:
    description: Give the all the privileges of mahime
    children:
      mahime.admin: true
  mahime.admin:
    description: Allow mahime commands.
    default: op